
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wilson
 */
public class boletin1ej21 extends javax.swing.JFrame {

    /**
     * Creates new form boletin1ej21
     */
    
    int n;
    
    public boletin1ej21() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Boletin 1 Ejercicio 22");

        jLabel2.setText("Nota");

        jLabel3.setText("Introduzca un número entre 0 y 99");

        jButton1.setText("Mostrar en letras");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        int u,d;
        
        n=Integer.parseInt(num.getText());
        
        u=n%10;
        d=n/10;
        
        switch(d){
            case 0: 
                    JOptionPane.showMessageDialog(null,
                   "",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
              case 1: 
                    JOptionPane.showMessageDialog(null,
                   "Diez",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 2: 
                    JOptionPane.showMessageDialog(null,
                   "Veinte",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 3: 
                    JOptionPane.showMessageDialog(null,
                   "Treinta",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 4: 
                    JOptionPane.showMessageDialog(null,
                   "Cuarenta",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 5: 
                    JOptionPane.showMessageDialog(null,
                   "Cincuenta",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 6: 
                    JOptionPane.showMessageDialog(null,
                   "Sesenta",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 7: 
                    JOptionPane.showMessageDialog(null,
                   "Setenta",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 8: 
                    JOptionPane.showMessageDialog(null,
                   "Ochenta",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 9: 
                    JOptionPane.showMessageDialog(null,
                   "Noventa",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
        }
         JOptionPane.showMessageDialog(null,
                   "y",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
          switch(u){          
                      case 0: 
                    JOptionPane.showMessageDialog(null,
                   "",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 1: 
                    JOptionPane.showMessageDialog(null,
                   "uno",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 2: 
                    JOptionPane.showMessageDialog(null,
                   "dos",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 3: 
                    JOptionPane.showMessageDialog(null,
                   "tres",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 4: 
                    JOptionPane.showMessageDialog(null,
                   "cuatro",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 5: 
                    JOptionPane.showMessageDialog(null,
                   "cinco",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 6: 
                    JOptionPane.showMessageDialog(null,
                   "seis",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 7: 
                    JOptionPane.showMessageDialog(null,
                   "siete",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 8: 
                    JOptionPane.showMessageDialog(null,
                   "ocho",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                      case 9: 
                    JOptionPane.showMessageDialog(null,
                   "nueve",
                    "Mensaje",
                    JOptionPane.WARNING_MESSAGE);  
                    break;
                    
                    
        
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boletin1ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boletin1ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boletin1ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boletin1ej21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new boletin1ej21().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField num;
    // End of variables declaration//GEN-END:variables
}
